### ISSUE TITLE
Soil Organic Carbon (SOC) Analysis

### ISSUE THREAD

**Issue by Em17y** [ktoddbrown/soils-long-tail-recovery#10]
This is a soil organic carbon analysis on the carbon levels in soil within fermented forests.

[pskoulgi/SOCanalysis](https://github.com/pskoulgi/SOCAnalysis)

Todo;
- [x]  Review and Decide if the Data will be Useful to the Master Project

**Comment by ktoddbrown** [comment]
No actual data in this repo. Just analysis scripts.
