### ISSUE TITLE
Bach et. al Grassland Affect on Soil Communities at Micro and Macro Scale

### ISSUE THREAD

**Issue by Em17y** [ktoddbrown/soils-long-tail-recovery#11]
This is a micro and macro analysis on the affect of soil fungal communities by nitrogen fertilization and grassland plant communities.

Note; this paper is still in submission.

[ITS_soil_landuse_aggregate](https://github.com/chnops/ITS_soil_landuse_aggregate)

Todo;
- [x]  Review and Decide if Data is Useful for the Master Project

**Comment by ktoddbrown** [comment]
This data set looks primarily at community composition. Data is beyond the scope of the project.
