### ISSUE TITLE
VAMPS

### ISSUE THREAD

**Issue by Em17y** [ktoddbrown/soils-long-tail-recovery#12]
Visualization and Analysis of Microbial Population Structures (Open Source License)

[avoorhis_VAMP](https://github.com/avoorhis/vamps-node.js)

Todo;
- [x]  Review and Decide if Useful for the Main Project

**Comment by ktoddbrown** [comment]
This is primarily concerned with visualization of microbial community data and not a data set in and of itself. Removing from potential lists of data sources.
