### ISSUE TITLE
Cong, et al. (2014)

### ISSUE THREAD

**Issue by SJTumber** [ktoddbrown/soils-long-tail-recovery#37]
http://datadryad.org/resource/doi:10.5061/dryad.p83h7

Title  Plant and soil data from the last year of the biodiversity experiment
Data from: Wen-feng Cong, Jasper van Ruijven, Liesje Mommer, Gerlinde De Deyn, Frank Berendse and Ellis Hoffland. (2014) Plant species richness promotes soil carbon and nitrogen stocks in grasslands without legumes. Data were collected in the 11-year grassland biodiversity experiment in Wageningen, the Netherlands, in 2010 and 2011. Abbreviated headlines are as follows: “”BLK”= block; “PT”= plot; "SR" = plant species richness; “MI” = monoculture identity (Ac = Agrostis capillaris; Ao = Anthoxanthum odoratum; Cj = Centaurea jacea; Fr = Festuca rubra; Hl = Holcus lanatus; Lv = Leucanthemum vulgare; Pl = Plantago lanceolata; Ra = Rumex acetosa); "AAB" = average aboveground biomass from 2000 to 2010 (g m-2); "RB" = standing root biomass (g fresh weight m-2) up to 50 cm depth in June 2010; "CS" = soil carbon stocks (g C m-2) in April 2011; "NS" = soil nitrogen stocks (g N m-2) in April 2011. "CD" = soil organic carbon decomposition (mg CO2-C kg-1 soil) measured in soil collected in April 2011; "NM" = potential net N mineralization rate (µg N kg-1 soil day-1) measured in soil collected in April 2011.

**Comment by ktoddbrown** [comment]
Thanks for identifying the data set! I've mvoed it to the new data table.
