### ISSUE TITLE
Moore, et al. (2015)

### ISSUE THREAD

**Issue by SJTumber** [ktoddbrown/soils-long-tail-recovery#38]
Data from: Interactions among roots, mycorrhizae and free-living microbial communities differentially impact soil carbon processes

Moore JAM, Jiang J, Patterson CM, Wang G, Mayes MA, Classen AT

Date Published: October 21, 2015

DOI: https://doi.org/10.5061/dryad.pb271

Soil respiration, soil carbon pools, and enzyme activities. The first row is a header and units of measurement are included in this row. In "exclusion group", R=roots and M= mycorrhizae. In "carbon label", C=control (water-only) and L=labeled starch addition.

**Comment by ktoddbrown** [comment]
merged reference into data table.
