### ISSUE TITLE
Hume, et al. (2017)

### ISSUE THREAD

**Issue by SJTumber** [ktoddbrown/soils-long-tail-recovery#40]
Data from: Intensive forest harvesting increases susceptibility of northern forest soils to carbon, nitrogen and phosphorus loss

Hume AM, Chen HYH, Taylor AR (2017) Intensive forest harvesting increases susceptibility of northern forest soils to carbon, nitrogen and phosphorus loss. Journal of Applied Ecology, online in advance of print. https://doi.org/10.1111/1365-2664.12942

http://datadryad.org/resource/doi:10.5061/dryad.dd602

**Comment by ktoddbrown** [comment]
Sorry that this took so long for me to get to. I added this to the data source tables. Thanks for the contribution!
