### ISSUE TITLE
Pommier, Thomas (2017)

### ISSUE THREAD

**Issue by marzipanwich** [ktoddbrown/soils-long-tail-recovery#41]
Measures of microbial, soil and plant variables of three grass-based agro-ecosystems in Austria, the UK and France (underrepresented regions)

https://doi.pangaea.de/10.1594/PANGAEA.879537

**Comment by ktoddbrown** [comment]
Sorry that this took me so long to get to! Thanks for the contribution! I've moved this over to the new data source table in this commit 05da41c50970a1ecefba5be47f342dd046a2d50a
