### ISSUE TITLE
Microorganism Mapping in Ecology 93

### ISSUE THREAD

**Issue by Em17y** [ktoddbrown/soils-long-tail-recovery#9]
This is a soil map of microorganisms using taxonomy and traits, from Lennon JT, Aanderud ZA, Lehmkuhl BK, and Schoolmaster DR (2012) in Ecology 93.

[LennonLab Soil Mapping](https://github.com/LennonLab/soil_traits)

Current Need;
- [ ]  Search and Decide on Use of Repository
- [ ]  Pull Dataset

**Comment by ktoddbrown** [comment]
Not relevant for this project. Data is focused on taxanomic associations.
